### ISSUE TITLE
Change obliteration.net domain from personal server to github server.

### ISSUE THREAD

**Issue by SoffiMeower** [obhq/obhq.github.io#4]
This will take me personally doing this with valid perms x3

**Comment by SoffiMeower** [comment]
Transferred obliteration.net from Porkbun to Cloudflare for easier DNS configuration and cheaper rates! Wooooooooo-

**Comment by ultimaweapon** [comment]
Here are the steps that need to be done on your side:

1. Create a TXT record in your DNS configuration for the following hostname: _github-pages-challenge-obhq.obliteration.net
2. Use this code for the value of the TXT record: c273ec1bfccc73150685c8b8d6c3fa
3. Wait until your DNS configuration changes. This could take up to 24 hours to propagate.

Let me know once you have completed this.

**Comment by SoffiMeower** [comment]
I uh, don't know if that works as I kinda also need to point ip and stuff-

**Comment by SoffiMeower** [comment]
Anyways uh, done.

**Comment by ultimaweapon** [comment]
Create a `CNAME` record for `www.obliteration.net` with value `obhq.github.io`. Let me know once you have completed this.

**Comment by SoffiMeower** [comment]
Done, SSL needs updated x3

**Comment by SoffiMeower** [comment]
JUST KIDDING

**Comment by SoffiMeower** [comment]
Now, one issue is uh- well... It's just using the Readme page for the website?

**Comment by ultimaweapon** [comment]
We need to fix the Action that publish it. Now this issue has been completed so I'll close it.
