### ISSUE TITLE
The compatibility list is not loading on Zen Browser (Firefox 131)

### ISSUE THREAD

**Issue by hardBSDk** [obhq/obhq.github.io#7]
The page is loaded but the items of the compatibility list don't.

- Web browser version - 1.0.1-a.12 (Firefox 131.0.3)
- OS - Fedora 40

https://zen-browser.app/

**Comment by ultimaweapon** [comment]
Removed by https://github.com/obhq/obhq.github.io/commit/f429d1539e6910fa820976a36875bfeed603fdd7.
